/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iia.isis;

import com.iia.osiris.database.BDD_Util;
import com.iia.osiris.metier.Salarie;
import com.iia.osiris.metier.Salle;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Darkadok
 */
public class NouvelleResa extends javax.swing.JFrame {

    ArrayList<Salle> listSalles = new ArrayList<>();
    private Salarie _responsable;

    public Salarie getResponsable() {
        return _responsable;
    }

    public void setResponsable(Salarie responsable) {
        this._responsable = responsable;
    }
    
    
    public NouvelleResa(Salarie responsable) {
        this.setResponsable(responsable);
        Connection cnx = null;
        Statement stmt = null;
        ResultSet ResultSalles = null;
        ResultSet ResultSalarie = null;
        ArrayList<Salarie> ListPersonne = new ArrayList<Salarie>();
        Salarie newSalarie = null;
        try {
            cnx = BDD_Util.open("root", "formation", "localhost", "GestionSalles");
            stmt = cnx.createStatement();
            ResultSalles = stmt.executeQuery("SELECT *  FROM Salle");
            stmt = cnx.createStatement();
            ResultSalarie = stmt.executeQuery("SELECT *  FROM Salarie");
        } catch (Exception ex) {
            System.out.println(ex.getStackTrace());
        }
        initComponents();
        try {
            this.jComboBox_Salle.removeAllItems();
            while (ResultSalles.next()) {
                this.jComboBox_Salle.addItem(new Salle(ResultSalles.getInt("Identifiant"), ResultSalles.getString("NumeroTerminal"), ResultSalles.getString("NomSalle"), null));
            }
            this.jComboBox_Salle.updateUI();

            this.jList_Personnes.removeAll();
            while (ResultSalarie.next()) {
                newSalarie = new Salarie(ResultSalarie.getInt("Identifiant"), ResultSalarie.getString("Nom"), ResultSalarie.getString("Prenom"), ResultSalarie.getString("Badge"), ResultSalarie.getBoolean("EstAdmin"));
                ListPersonne.add(newSalarie);
            }
            this.jList_Personnes.setListData(ListPersonne.toArray());
            jList_Personnes.updateUI();

            cnx.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            javax.swing.JOptionPane.showMessageDialog(null, ex.getStackTrace(), "Error", 0);
            this.setVisible(false);
            this.dispose();
        }
        this.jComboBox_Salle.setSelectedIndex(-1);
        cnx = null;
        stmt = null;
        ResultSalles = null;
        ResultSalarie = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Salle = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_Personnes = new javax.swing.JList();
        jButton_Annuler = new javax.swing.JButton();
        jButton_ok = new javax.swing.JButton();
        jButton_RAZ = new javax.swing.JButton();
        jComboBox_Deb = new javax.swing.JComboBox();
        jComboBox_fin = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_Chercher = new javax.swing.JButton();
        jSCDatePicker1 = new com.javaswingcomponents.datepicker.JSCDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Réserver une salle");

        jLabel1.setText("Date");

        jLabel2.setText("Salle");

        jLabel4.setText("Personnes autorisées");

        jComboBox_Salle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jList_Personnes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList_Personnes.setEnabled(false);
        jScrollPane1.setViewportView(jList_Personnes);

        jButton_Annuler.setText("Annuler");
        jButton_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnnulerActionPerformed(evt);
            }
        });

        jButton_ok.setText("OK");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        jButton_RAZ.setLabel("RàZ");
        jButton_RAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RAZActionPerformed(evt);
            }
        });

        jComboBox_Deb.setEnabled(false);

        jComboBox_fin.setEnabled(false);

        jLabel5.setText("Heure de début");

        jLabel6.setText("Heure de fin");

        jButton_Chercher.setText("Chercher disponibilités");
        jButton_Chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_RAZ)
                        .addGap(129, 129, 129)
                        .addComponent(jButton_Chercher))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSCDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox_Salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_Deb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Annuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_ok))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(320, 320, 320))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSCDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_RAZ)
                                    .addComponent(jButton_Chercher)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox_Salle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox_Deb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(jComboBox_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Annuler)
                    .addComponent(jButton_ok)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        Connection cnx = null;
        PreparedStatement prestmt;
        ResultSet rs = null;
        int IntDateDeb = -1;
        int IntDateFin = -1;
        int identifiant_jour = -1;
        int idReservation = -1;
        boolean isPossible = true;
        if (this.jComboBox_Salle.getSelectedIndex() >= 0 && this.jSCDatePicker1.getSelectedDate() != null) {
            IntDateDeb = Integer.parseInt(((String) jComboBox_Deb.getSelectedItem()).substring(0, 2).trim());
            IntDateFin = Integer.parseInt(((String) jComboBox_fin.getSelectedItem()).substring(0, 2).trim());
            if (IntDateDeb > IntDateFin) {
                javax.swing.JOptionPane.showMessageDialog(null, "Veuillez choisir une heure de fin postérieure à l'heure de début ", "Attention !", 2);
            } else {

                try {
                    cnx = BDD_Util.open("root", "formation", "localhost", "GestionSalles");
                    int tmp = IntDateDeb;
                    while (tmp <= IntDateFin && isPossible) {
                        prestmt = cnx.prepareStatement("SELECT identifiant FROM reservation WHERE dateRes = ? AND HoraireDeb <= ? AND HoraireFin > ? AND IdentifiantSalle = ?;");
                        prestmt.setDate(1, new java.sql.Date(this.jSCDatePicker1.getCalendar().getSelectedDate().getTime()));
                        prestmt.setTime(2, new Time(tmp, 0, 0));
                        prestmt.setTime(3, new Time(tmp, 0, 0));
                        prestmt.setInt(4, ((Salle) this.jComboBox_Salle.getSelectedItem()).getIdentifiant());
                        rs = prestmt.executeQuery();

                        if (rs.next()) {
                            isPossible = false;
                        }
                        tmp++;
                    }
                } catch (Exception ex) {
                    Logger.getLogger(NouvelleResa.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (isPossible) {
                    try {
                        cnx.setAutoCommit(false);
                        identifiant_jour = jSCDatePicker1.getSelectedDate().getDay();
                        prestmt = cnx.prepareStatement("INSERT INTO reservation VALUES (NULL,?,?,?,?,?,?); ", Statement.RETURN_GENERATED_KEYS);
                        prestmt.setDate(1, new java.sql.Date(this.jSCDatePicker1.getSelectedDate().getTime()));
                        prestmt.setTime(2, new Time(IntDateDeb, 0, 0));
                        prestmt.setTime(3, new Time(IntDateFin, 59, 00));
                        prestmt.setInt(4, identifiant_jour);
                        prestmt.setInt(5, this.getResponsable().getIdentifiant());
                        prestmt.setInt(6, ((Salle) jComboBox_Salle.getSelectedItem()).getIdentifiant());
                        prestmt.executeUpdate();
                        cnx.commit();
                        ResultSet tmpSet = prestmt.getGeneratedKeys();
                        tmpSet.next();
                        idReservation = tmpSet.getInt(1);
                        tmpSet = null;
                        for (Salarie selected : (ArrayList<Salarie>) jList_Personnes.getSelectedValuesList()) {
                            prestmt = cnx.prepareStatement("INSERT INTO autorise VALUES (?,?);");
                            prestmt.setInt(1, selected.getIdentifiant());
                            prestmt.setInt(2, idReservation);
                            prestmt.executeUpdate();
                            cnx.commit();
                        }
                        javax.swing.JOptionPane.showMessageDialog(null, "Réservation effectuée avec succès !", "Information !", 1);
                        prestmt = null;
                        cnx.close();

                        this.setVisible(false);
                        this.dispose();
                    } catch (Exception ex) {
                        System.out.println(ex.getStackTrace());
                        try {
                            cnx.rollback();
                        } catch (SQLException ex1) {
                            System.out.println(ex1.getStackTrace());
                        }
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(null, "Un réservation existe déjà pour cet horaire", "Attention !", 2);
                }

                try {
                    cnx.close();
                } catch (SQLException ex) {
                    Logger.getLogger(NouvelleResa.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Veuillez remplir tout les champs", "Attention !", 2);
        }

    }//GEN-LAST:event_jButton_okActionPerformed

    private void jButton_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnnulerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton_AnnulerActionPerformed

    private void jButton_RAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RAZActionPerformed
        this.jList_Personnes.clearSelection();
        this.jComboBox_Salle.setSelectedIndex(-1);
        this.jSCDatePicker1.setSelectedDate(null);
        jComboBox_Deb.setEnabled(false);
        jComboBox_fin.setEnabled(false);
        jList_Personnes.setEnabled(false);
        jComboBox_Deb.removeAllItems();
        jComboBox_fin.removeAllItems();
    }//GEN-LAST:event_jButton_RAZActionPerformed

    private void jButton_ChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChercherActionPerformed
        Connection cnx = null;
        PreparedStatement prestmt = null;
        ResultSet result = null;
        ResultSet resultDejaReserve = null;
        Time heurDeb1 = null;
        Time heurDeb2 = null;
        Time heurFin1 = null;
        Time heurFin2 = null;
        int tmp = -1;

        if (jComboBox_Salle.getSelectedIndex() >= 0) {
            jComboBox_Deb.setEnabled(true);
            jComboBox_fin.setEnabled(true);
            jList_Personnes.setEnabled(true);
            jComboBox_Deb.removeAllItems();
            jComboBox_fin.removeAllItems();
            try {
                cnx = BDD_Util.open("root", "formation", "localhost", "GestionSalles");
                prestmt = cnx.prepareStatement("SELECT * FROM disponibilite WHERE identifiantSalle = ?;");
                prestmt.setInt(1, ((Salle) jComboBox_Salle.getSelectedItem()).getIdentifiant());
                result = prestmt.executeQuery();
                while (result.next()) {
                    heurDeb1 = result.getTime("HoraireDebMat");
                    heurDeb2 = result.getTime("HoraireDebSoir");
                    heurFin1 = result.getTime("HoraireFinMat");
                    heurFin2 = result.getTime("HoraireFinSoir");

                    if (heurDeb1 != null && heurFin1 != null) {
                        tmp = heurDeb1.getHours();
                        while (tmp <= heurFin1.getHours()) {

                            jComboBox_Deb.addItem(tmp + " : 00");
                            jComboBox_fin.addItem(tmp + " : 59");
                            tmp++;
                        }
                    }
                    if (heurDeb2 != null && heurFin2 != null) {
                        tmp = heurDeb2.getHours();
                        while (tmp <= heurFin2.getHours()) {
                            jComboBox_Deb.addItem(tmp + " : 00");
                            jComboBox_fin.addItem(tmp + " : 59");
                            tmp++;
                        }
                    }
                }
            } catch (Exception ex) {
                System.out.println(ex.getStackTrace());
            }
        }
    }//GEN-LAST:event_jButton_ChercherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NouvelleResa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NouvelleResa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NouvelleResa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NouvelleResa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Annuler;
    private javax.swing.JButton jButton_Chercher;
    private javax.swing.JButton jButton_RAZ;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JComboBox jComboBox_Deb;
    private javax.swing.JComboBox jComboBox_Salle;
    private javax.swing.JComboBox jComboBox_fin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList_Personnes;
    private javax.swing.JPanel jPanel1;
    private com.javaswingcomponents.datepicker.JSCDatePicker jSCDatePicker1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
