/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iia.osiris.ihm;

import com.iia.osiris.database.BDD_Util;
import com.iia.osiris.database.SalarieDAO;
import com.iia.osiris.metier.Salarie;
import java.sql.Connection;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Akimar
 */
public class AjoutSalarie extends javax.swing.JDialog {

        
    private Vector<Salarie> vectorSalarie;
    /**
     * Creates new form test
     */
    public AjoutSalarie(java.awt.Frame parent, boolean modal, Vector<Salarie> vS) {
        super(parent, modal);
        initComponents();
        
        vectorSalarie = vS;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminGroup = new javax.swing.ButtonGroup();
        ajoutSalariePanel = new javax.swing.JPanel();
        nomSalarieLabel = new javax.swing.JLabel();
        prenomSalarieLabel = new javax.swing.JLabel();
        badgeSalarieLabel = new javax.swing.JLabel();
        adminSalarieLabel = new javax.swing.JLabel();
        titreLabel = new javax.swing.JLabel();
        estAdminRadio = new javax.swing.JRadioButton();
        nonAdminRadio = new javax.swing.JRadioButton();
        nomSalarieField = new javax.swing.JTextField();
        prenomSalarieField = new javax.swing.JTextField();
        badgeSalarieField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        validerAjoutSalarie = new javax.swing.JButton();
        annulerAjoutSalarie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        nomSalarieLabel.setText("Nom : ");

        prenomSalarieLabel.setText("Prénom : ");

        badgeSalarieLabel.setText("Badge : ");

        adminSalarieLabel.setText("Administrateur : ");

        titreLabel.setText("Ajouter un salarié");

        adminGroup.add(estAdminRadio);
        estAdminRadio.setText("Oui");

        adminGroup.add(nonAdminRadio);
        nonAdminRadio.setSelected(true);
        nonAdminRadio.setText("Non");

        javax.swing.GroupLayout ajoutSalariePanelLayout = new javax.swing.GroupLayout(ajoutSalariePanel);
        ajoutSalariePanel.setLayout(ajoutSalariePanelLayout);
        ajoutSalariePanelLayout.setHorizontalGroup(
            ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutSalariePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoutSalariePanelLayout.createSequentialGroup()
                        .addComponent(adminSalarieLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(estAdminRadio)
                        .addGap(18, 18, 18)
                        .addComponent(nonAdminRadio))
                    .addGroup(ajoutSalariePanelLayout.createSequentialGroup()
                        .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenomSalarieLabel)
                            .addComponent(nomSalarieLabel)
                            .addComponent(badgeSalarieLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prenomSalarieField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(badgeSalarieField)
                            .addComponent(nomSalarieField))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajoutSalariePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titreLabel)
                .addGap(58, 58, 58))
        );
        ajoutSalariePanelLayout.setVerticalGroup(
            ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutSalariePanelLayout.createSequentialGroup()
                .addComponent(titreLabel)
                .addGap(15, 15, 15)
                .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomSalarieLabel)
                    .addComponent(nomSalarieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomSalarieLabel)
                    .addComponent(prenomSalarieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(badgeSalarieLabel)
                    .addComponent(badgeSalarieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminSalarieLabel)
                    .addComponent(estAdminRadio)
                    .addComponent(nonAdminRadio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        validerAjoutSalarie.setText("Ajouter");
        validerAjoutSalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerAjoutSalarieActionPerformed(evt);
            }
        });

        annulerAjoutSalarie.setText("Annuler");
        annulerAjoutSalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerAjoutSalarieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(validerAjoutSalarie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(annulerAjoutSalarie)
                .addGap(23, 23, 23))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validerAjoutSalarie)
                    .addComponent(annulerAjoutSalarie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(ajoutSalariePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajoutSalariePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerAjoutSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerAjoutSalarieActionPerformed
        // TODO add your handling code here:
          
        if(nomSalarieField.getText().isEmpty() || prenomSalarieField.getText().isEmpty() || badgeSalarieField.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Veuillez compléter tous les champs.");
        }
        
        else if(!nomSalarieField.getText().matches("[a-zA-ZÀ-ÿ\\- ]+") || !prenomSalarieField.getText().matches("[a-zA-ZÀ-ÿ\\- ]+") || !badgeSalarieField.getText().matches("[A-Za-z0-9]+"))
        {
           JOptionPane.showMessageDialog(null, "Les informations contiennent des caractères non pris en compte");
        }
   
        else
        {
            int i = 0;
            boolean dejaPresent = false;
            while(i < vectorSalarie.size() && ! dejaPresent)
            {
                if(vectorSalarie.elementAt(i).badgeExists(badgeSalarieField.getText()))
                {
                    dejaPresent = true;
                }
                
                i++;
            }
            
            if(!dejaPresent)
            {
                int id;
                boolean admin = (nonAdminRadio.isSelected()) ? false : true;
            
                try 
                {
                    Connection cnx = BDD_Util.open("root", "formation", "localhost", "GestionSalles");
                    id = SalarieDAO.addSalarie(cnx,nomSalarieField.getText(), prenomSalarieField.getText(), badgeSalarieField.getText(), admin);
                    cnx.close();
                    cnx=null;

                    if(id != -1)
                    {
                        vectorSalarie.add(new Salarie(id, nomSalarieField.getText(), prenomSalarieField.getText(), badgeSalarieField.getText(), admin));
                        JOptionPane.showMessageDialog(null, "Le salarié a été ajouté avec succès !");
                    }   
                } 
                catch (Exception ex) 
                {
                    JOptionPane.showMessageDialog(null, "Une erreur s'est produite, l'enregistrement a échoué.");
                }

                finally
                {
                  this.dispose();
                }
            }
            
            else
            {
               JOptionPane.showMessageDialog(null, "Le numéro de badge saisi est déjà utilisé.");
            }
        }
        
        
    }//GEN-LAST:event_validerAjoutSalarieActionPerformed

    private void annulerAjoutSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerAjoutSalarieActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_annulerAjoutSalarieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup adminGroup;
    private javax.swing.JLabel adminSalarieLabel;
    private javax.swing.JPanel ajoutSalariePanel;
    private javax.swing.JButton annulerAjoutSalarie;
    private javax.swing.JTextField badgeSalarieField;
    private javax.swing.JLabel badgeSalarieLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JRadioButton estAdminRadio;
    private javax.swing.JTextField nomSalarieField;
    private javax.swing.JLabel nomSalarieLabel;
    private javax.swing.JRadioButton nonAdminRadio;
    private javax.swing.JTextField prenomSalarieField;
    private javax.swing.JLabel prenomSalarieLabel;
    private javax.swing.JLabel titreLabel;
    private javax.swing.JButton validerAjoutSalarie;
    // End of variables declaration//GEN-END:variables
}
