/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iia.osiris.ihm;

import com.iia.osiris.database.BDD_Util;
import com.iia.osiris.database.SalarieDAO;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Akimar
 */
public class AjoutSalarie extends javax.swing.JFrame {

    /**
     * Creates new form AjoutSalarie
     */
    public AjoutSalarie() {
        initComponents();
        
        errorNameLabel.setVisible(false);
        errorFirstNameLabel.setVisible(false);
        errorBadgeLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminGroup = new javax.swing.ButtonGroup();
        buttonPanel = new javax.swing.JPanel();
        validerAjoutSalarie = new javax.swing.JButton();
        annulerAjoutSalarie = new javax.swing.JButton();
        ajoutSalariePanel = new javax.swing.JPanel();
        nomSalarieLabel = new javax.swing.JLabel();
        prenomSalarieLabel = new javax.swing.JLabel();
        badgeSalarieLabel = new javax.swing.JLabel();
        adminSalarieLabel = new javax.swing.JLabel();
        titreLabel = new javax.swing.JLabel();
        estAdminRadio = new javax.swing.JRadioButton();
        nonAdminRadio = new javax.swing.JRadioButton();
        nomSalarieField = new javax.swing.JTextField();
        prenomSalarieField = new javax.swing.JTextField();
        badgeSalarieField = new javax.swing.JTextField();
        errorPanel = new javax.swing.JPanel();
        errorFirstNameLabel = new javax.swing.JLabel();
        errorNameLabel = new javax.swing.JLabel();
        errorBadgeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Osiris");
        setResizable(false);

        validerAjoutSalarie.setText("Ajouter");
        validerAjoutSalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerAjoutSalarieActionPerformed(evt);
            }
        });

        annulerAjoutSalarie.setText("Annuler");
        annulerAjoutSalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerAjoutSalarieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(validerAjoutSalarie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(annulerAjoutSalarie)
                .addGap(41, 41, 41))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validerAjoutSalarie)
                    .addComponent(annulerAjoutSalarie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomSalarieLabel.setText("Nom : ");

        prenomSalarieLabel.setText("Prénom : ");

        badgeSalarieLabel.setText("Badge : ");

        adminSalarieLabel.setText("Administrateur : ");

        titreLabel.setText("Ajouter un salarié");

        adminGroup.add(estAdminRadio);
        estAdminRadio.setText("Oui");

        adminGroup.add(nonAdminRadio);
        nonAdminRadio.setSelected(true);
        nonAdminRadio.setText("Non");

        nomSalarieField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nomSalarieFieldCaretUpdate(evt);
            }
        });

        prenomSalarieField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                prenomSalarieFieldCaretUpdate(evt);
            }
        });

        badgeSalarieField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                badgeSalarieFieldCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout ajoutSalariePanelLayout = new javax.swing.GroupLayout(ajoutSalariePanel);
        ajoutSalariePanel.setLayout(ajoutSalariePanelLayout);
        ajoutSalariePanelLayout.setHorizontalGroup(
            ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutSalariePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoutSalariePanelLayout.createSequentialGroup()
                        .addComponent(adminSalarieLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(estAdminRadio)
                        .addGap(18, 18, 18)
                        .addComponent(nonAdminRadio))
                    .addGroup(ajoutSalariePanelLayout.createSequentialGroup()
                        .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenomSalarieLabel)
                            .addComponent(nomSalarieLabel)
                            .addComponent(badgeSalarieLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prenomSalarieField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(badgeSalarieField)
                            .addComponent(nomSalarieField)))
                    .addComponent(titreLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ajoutSalariePanelLayout.setVerticalGroup(
            ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutSalariePanelLayout.createSequentialGroup()
                .addComponent(titreLabel)
                .addGap(15, 15, 15)
                .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomSalarieLabel)
                    .addComponent(nomSalarieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomSalarieLabel)
                    .addComponent(prenomSalarieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(badgeSalarieLabel)
                    .addComponent(badgeSalarieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ajoutSalariePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminSalarieLabel)
                    .addComponent(estAdminRadio)
                    .addComponent(nonAdminRadio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        errorFirstNameLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorFirstNameLabel.setText("Caractères interdits !");

        errorNameLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorNameLabel.setText("Caractères interdits !");

        errorBadgeLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorBadgeLabel.setText("Format incorrect !");

        javax.swing.GroupLayout errorPanelLayout = new javax.swing.GroupLayout(errorPanel);
        errorPanel.setLayout(errorPanelLayout);
        errorPanelLayout.setHorizontalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorBadgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorFirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        errorPanelLayout.setVerticalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, errorPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(errorNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(errorFirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(errorBadgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajoutSalariePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(errorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ajoutSalariePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(errorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerAjoutSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerAjoutSalarieActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_annulerAjoutSalarieActionPerformed

    private void validerAjoutSalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerAjoutSalarieActionPerformed
        // TODO add your handling code here:
        
        if(nomSalarieField.getText().isEmpty() || prenomSalarieField.getText().isEmpty() || badgeSalarieField.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "Veuillez compléter tous les champs.");
        }
        
        else if(!errorBadgeLabel.isVisible() && !errorFirstNameLabel.isVisible() && !errorNameLabel.isVisible())
        {
            boolean admin = (nonAdminRadio.isSelected()) ? false : true;
            
          
          
            Connection cnx;
            try 
            {
                cnx = BDD_Util.open("root", "formation", "localhost", "GestionSalles");
                
                SalarieDAO.addSalarie(cnx,nomSalarieField.getText(), prenomSalarieField.getText(), badgeSalarieField.getText(), admin);
                
                cnx.close();
                cnx=null;
                
                
            } 
            catch (Exception ex) 
            {
                Logger.getLogger(AjoutSalarie.class.getName()).log(Level.SEVERE, null, ex);
            }
            
          
        }
    }//GEN-LAST:event_validerAjoutSalarieActionPerformed

    private void nomSalarieFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nomSalarieFieldCaretUpdate
        // TODO add your handling code here:
        if(!nomSalarieField.getText().matches("[a-zA-ZÀ-ÿ\\- ]+") && !nomSalarieField.getText().isEmpty())
        {
            errorNameLabel.setVisible(true);
        }
        
        else
        {
            errorNameLabel.setVisible(false);
        }
    }//GEN-LAST:event_nomSalarieFieldCaretUpdate

    private void prenomSalarieFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_prenomSalarieFieldCaretUpdate
        // TODO add your handling code here:
        
        if(!prenomSalarieField.getText().matches("[a-zA-ZÀ-ÿ\\- ]+") && !prenomSalarieField.getText().isEmpty())
        {
            errorFirstNameLabel.setVisible(true);
        }
        
        else
        {
            errorFirstNameLabel.setVisible(false);
        }
    }//GEN-LAST:event_prenomSalarieFieldCaretUpdate

    private void badgeSalarieFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_badgeSalarieFieldCaretUpdate
        // TODO add your handling code here:
        
        if(!badgeSalarieField.getText().matches("[A-Za-z0-9]+") && !badgeSalarieField.getText().isEmpty())
        {
            errorBadgeLabel.setVisible(true);
        }
        
        else
        {
            errorBadgeLabel.setVisible(false);
        }
    }//GEN-LAST:event_badgeSalarieFieldCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup adminGroup;
    private javax.swing.JLabel adminSalarieLabel;
    private javax.swing.JPanel ajoutSalariePanel;
    private javax.swing.JButton annulerAjoutSalarie;
    private javax.swing.JTextField badgeSalarieField;
    private javax.swing.JLabel badgeSalarieLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel errorBadgeLabel;
    private javax.swing.JLabel errorFirstNameLabel;
    private javax.swing.JLabel errorNameLabel;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JRadioButton estAdminRadio;
    private javax.swing.JTextField nomSalarieField;
    private javax.swing.JLabel nomSalarieLabel;
    private javax.swing.JRadioButton nonAdminRadio;
    private javax.swing.JTextField prenomSalarieField;
    private javax.swing.JLabel prenomSalarieLabel;
    private javax.swing.JLabel titreLabel;
    private javax.swing.JButton validerAjoutSalarie;
    // End of variables declaration//GEN-END:variables
}
