/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iia.osiris.ihm;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Akimar
 */
public class DisponibiliteFrame extends javax.swing.JFrame {

    /**
     * Creates new form DisponibiliteFrame
     */
    public DisponibiliteFrame() {
        initComponents();
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreLabel = new javax.swing.JLabel();
        joursComboBox = new javax.swing.JComboBox();
        dispoPanel = new javax.swing.JPanel();
        matinLabel = new javax.swing.JLabel();
        soirLabel = new javax.swing.JLabel();
        Date dateMatDeb = new Date();
        SpinnerDateModel smMatDeb =
        new SpinnerDateModel(dateMatDeb, null, null, Calendar.HOUR_OF_DAY);
        HoraireMatDebSpinner = new javax.swing.JSpinner(smMatDeb);
        Date dateSoirDeb = new Date();
        SpinnerDateModel smSoirDeb =
        new SpinnerDateModel(dateSoirDeb, null, null, Calendar.HOUR_OF_DAY);
        HoraireSoirDebSpinner = new javax.swing.JSpinner(smSoirDeb);
        Date dateMatFin = new Date();
        SpinnerDateModel smMatFin =
        new SpinnerDateModel(dateMatFin, null, null, Calendar.HOUR_OF_DAY);
        HoraireMatFinSpinner = new javax.swing.JSpinner(smMatFin);
        Date dateSoirFin = new Date();
        SpinnerDateModel smSoirFin =
        new SpinnerDateModel(dateSoirFin, null, null, Calendar.HOUR_OF_DAY);
        HoraireSoirFinSpinner = new javax.swing.JSpinner(smSoirFin);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titreLabel.setText("Disponibilités");
        titreLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        joursComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche" }));

        matinLabel.setText("Matin : ");

        soirLabel.setText("Après-midi : ");

        JSpinner.DateEditor deMatDeb = new JSpinner.DateEditor(HoraireMatDebSpinner, "HH:mm:ss");
        HoraireMatDebSpinner.setEditor(deMatDeb);

        JSpinner.DateEditor deSoirDeb = new JSpinner.DateEditor(HoraireSoirDebSpinner, "HH:mm:ss");
        HoraireSoirDebSpinner.setEditor(deSoirDeb);

        JSpinner.DateEditor deMatFin = new JSpinner.DateEditor(HoraireMatFinSpinner, "HH:mm:ss");
        HoraireMatFinSpinner.setEditor(deMatFin);

        JSpinner.DateEditor deSoirFin = new JSpinner.DateEditor(HoraireSoirFinSpinner, "HH:mm:ss");
        HoraireSoirFinSpinner.setEditor(deSoirFin);

        javax.swing.GroupLayout dispoPanelLayout = new javax.swing.GroupLayout(dispoPanel);
        dispoPanel.setLayout(dispoPanelLayout);
        dispoPanelLayout.setHorizontalGroup(
            dispoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dispoPanelLayout.createSequentialGroup()
                .addGroup(dispoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dispoPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(matinLabel)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dispoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(soirLabel)
                        .addGap(18, 18, 18)))
                .addGroup(dispoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HoraireMatDebSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(HoraireSoirDebSpinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(dispoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HoraireMatFinSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(HoraireSoirFinSpinner))
                .addGap(43, 43, 43))
        );
        dispoPanelLayout.setVerticalGroup(
            dispoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dispoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dispoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matinLabel)
                    .addComponent(HoraireMatDebSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoraireMatFinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(dispoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soirLabel)
                    .addComponent(HoraireSoirDebSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoraireSoirFinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(titreLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(joursComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dispoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreLabel)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(joursComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dispoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisponibiliteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisponibiliteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisponibiliteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisponibiliteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisponibiliteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner HoraireMatDebSpinner;
    private javax.swing.JSpinner HoraireMatFinSpinner;
    private javax.swing.JSpinner HoraireSoirDebSpinner;
    private javax.swing.JSpinner HoraireSoirFinSpinner;
    private javax.swing.JPanel dispoPanel;
    private javax.swing.JComboBox joursComboBox;
    private javax.swing.JLabel matinLabel;
    private javax.swing.JLabel soirLabel;
    private javax.swing.JLabel titreLabel;
    // End of variables declaration//GEN-END:variables
}
