/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iia.osiris.ihm;

import com.iia.osiris.database.BDD_Util;
import com.iia.osiris.database.SalleDAO;
import com.iia.osiris.metier.Salle;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Akimar
 */
public class ModifierSalle extends javax.swing.JDialog {
    
    private Vector<Salle> vectorSalle;
    private int indexSalle;
      
    /**
     * Creates new form ModifierSalle
     */
    public ModifierSalle(java.awt.Frame parent, boolean modal, Vector<Salle> vS, int index) {
        super(parent, modal);
        initComponents();
        
       vectorSalle = vS;
       indexSalle = index ;
       
        this.terminalField.setText(vectorSalle.elementAt(indexSalle).getNumeroTerminal());
        this.salleField.setText(vectorSalle.elementAt(indexSalle).getNom());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titreLabel = new javax.swing.JLabel();
        modfifPanel = new javax.swing.JPanel();
        salleLabel = new javax.swing.JLabel();
        terminalLabel = new javax.swing.JLabel();
        salleField = new javax.swing.JTextField();
        terminalField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        validerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titreLabel.setText("Modifier les informations d'une salle et d'un terminal");

        salleLabel.setText("Nom de la salle : ");

        terminalLabel.setText("Numéro du terminal : ");

        javax.swing.GroupLayout modfifPanelLayout = new javax.swing.GroupLayout(modfifPanel);
        modfifPanel.setLayout(modfifPanelLayout);
        modfifPanelLayout.setHorizontalGroup(
            modfifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modfifPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(modfifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(terminalLabel)
                    .addComponent(salleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modfifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salleField)
                    .addComponent(terminalField))
                .addGap(59, 59, 59))
        );
        modfifPanelLayout.setVerticalGroup(
            modfifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modfifPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(modfifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salleLabel)
                    .addComponent(salleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(modfifPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terminalLabel)
                    .addComponent(terminalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        validerButton.setText("Modifier");
        validerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerButtonActionPerformed(evt);
            }
        });

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(validerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(annulerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validerButton)
                    .addComponent(annulerButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modfifPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titreLabel)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreLabel)
                .addGap(18, 18, 18)
                .addComponent(modfifPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed
        // TODO add your handling code here:
        
        // vérifie qu'aucun champ n'est laissé vide
          if(terminalField.getText().isEmpty() || salleField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Veuillez compléter tous les champs.");
        }
        
        // contrôle les saisies
        else if(!terminalField.getText().matches("[0-9]+") || !salleField.getText().matches("[a-zA-Z0-9]+"))
        {
           JOptionPane.showMessageDialog(null, "Les informations contiennent des caractères non pris en compte.");
        }
        else
        {
       
            Connection cnx=null;
  
            try 
            {

                cnx = BDD_Util.open("root", "formation", "localhost", "GestionSalles");
                SalleDAO.updateSalle(cnx, vectorSalle.elementAt(indexSalle).getIdentifiant(), this.terminalField.getText(), this.salleField.getText());// mise à jour en base
                
                // mise à jour en mémoire
                vectorSalle.elementAt(indexSalle).setNumeroTerminal(this.terminalField.getText());
                vectorSalle.elementAt(indexSalle).setNom(this.salleField.getText());

                JOptionPane.showMessageDialog(null, "Les informations ont été modifiées avec succès !");
            } 
            catch (Exception ex) 
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Une erreur s'est produite, les modifications ont échoué.");
            }

            finally
            {
                if(cnx != null)
                {
                    try
                    {
                        cnx.close();
                        cnx = null;
                    }

                    catch(SQLException ex)
                    {
                        ex.printStackTrace();
                    }
                }

                this.dispose();
            } 
        }
    }//GEN-LAST:event_validerButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel modfifPanel;
    private javax.swing.JTextField salleField;
    private javax.swing.JLabel salleLabel;
    private javax.swing.JTextField terminalField;
    private javax.swing.JLabel terminalLabel;
    private javax.swing.JLabel titreLabel;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables
}
